Schema fixes
teleskope/teleskope pull request #60
Opened 2019-04-25 22:47 UTC by joshnwalters

2019-04-25 23:22 UTC, mattkim009 approved these changes

2019-04-26 01:12 UTC, mattkim009 requested changes
Add more info to the defaultProfiles

2019-04-26 03:10 UTC, j-taki commented on config/settings.development.json
> +      "skille": "Bioinformatics",
@joshnwalters typo

2019-04-26 03:11 UTC, mattkim009 commented on config/settings.development.json
> +      "skille": "Bioinformatics",
I'll take care of that

2019-04-26 03:12 UTC, j-taki approved these changes

2019-04-26 03:12 UTC, joshnwalters commented on config/settings.development.json
> +      "skille": "Bioinformatics",
fixed skille

2019-04-26 05:07 UTC, mattkim009 approved these changes

2019-04-26 05:07 UTC, merged